# Generated by Django 4.1.7 on 2023-02-24 23:23

from django.db import migrations, models
import tim.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_1', models.DateTimeField(blank=True, null=True)),
                ('dept_2', models.DateTimeField(blank=True, null=True)),
                ('dept_3', models.DateTimeField(blank=True, null=True)),
                ('dept_4', models.DateTimeField(blank=True, null=True)),
                ('dept_5', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=30, verbose_name=tim.models.Department)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
