# Generated by Django 4.1.7 on 2023-02-25 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in', models.DateField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('dept_1', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in', models.DateField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('dept_1', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_2',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_3',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_4',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_5',
        ),
        migrations.AddField(
            model_name='department',
            name='day_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_1',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
