# Generated by Django 4.1.7 on 2023-02-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim', '0004_alter_department_dept_1_alter_department2_dept_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department2',
            old_name='dept_1',
            new_name='dept_2',
        ),
        migrations.RenameField(
            model_name='department3',
            old_name='dept_1',
            new_name='dept_3',
        ),
    ]
