# Generated by Django 4.1.7 on 2023-02-25 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tim', '0005_rename_dept_1_department2_dept_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_select', models.CharField(blank=True, choices=[('department1', 'department1'), ('department2', 'department2'), ('department3', 'department3')], max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_1',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department2',
            name='dept_2',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department3',
            name='dept_3',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
