# Generated by Django 4.1.7 on 2023-02-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim', '0006_selectdept_alter_department_dept_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectDept',
        ),
    ]
