# Generated by Django 4.1.7 on 2023-02-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tim', '0007_delete_selectdept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department3',
            name='dept_3',
        ),
        migrations.RemoveField(
            model_name='department',
            name='day_in',
        ),
        migrations.RemoveField(
            model_name='department',
            name='time_in',
        ),
        migrations.DeleteModel(
            name='Department2',
        ),
        migrations.DeleteModel(
            name='Department3',
        ),
    ]
