# Generated by Django 4.1.7 on 2023-03-01 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tim', '0008_remove_department3_dept_3_remove_department_day_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='day_in',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='time_in',
            field=models.TimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Department3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(auto_created=True, blank=True, null=True)),
                ('day_in', models.DateField(auto_created=True, blank=True, null=True)),
                ('dept_3', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(auto_created=True, blank=True, null=True)),
                ('day_in', models.DateField(auto_created=True, blank=True, null=True)),
                ('dept_2', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
