# Generated by Django 4.1.7 on 2023-03-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tim', '0011_department_logout_department2_logout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='logout',
            field=models.TimeField(auto_now=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='department2',
            name='logout',
            field=models.TimeField(auto_now=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='department3',
            name='logout',
            field=models.TimeField(auto_now=True, max_length=8),
        ),
    ]
